#include "wire/link_ready.hpp"
#include "wire/p256_point.hpp"
#include "wire/sha256.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

/*
 * LINK_READY_V1 exact codec. The golden vectors below are hard-coded constants
 * generated by the independent script out/logs/gen_golden.ps1; nothing here is
 * ever produced by the codec under test.
 */

namespace {

namespace wire = flynes::session::wire;
namespace link = flynes::session::link;

int failures = 0;

void check(bool value, const char* message)
{
    if (!value) {
        std::fprintf(stderr, "FAIL: %s\n", message);
        ++failures;
    }
}

// kHelloInitiatorObjectHash (32 bytes)
constexpr const char* kHelloInitiatorObjectHash =
        "e68b03ee77136754df1445d6fc1a215b6b4b787fad8819eb1b04b9a805c872c3"
    ;


// kHelloResponderObjectHash (32 bytes)
constexpr const char* kHelloResponderObjectHash =
        "aa10adeee6a6d6586e444206382b47e52bbfd3e3155fb45648fe452c81c51375"
    ;


// kReadyInitiatorBytes (432 bytes)
constexpr const char* kReadyInitiatorBytes =
            "0001000000000000010202010000000011111111111111111111111111111111"
    "2222222222222222222222222222222201020304050607080000000000000000"
    "0000000000000007000000000000000000000000000000098888888888888888"
    "888888888888888888888888888888888888888888888888e68b03ee77136754"
    "df1445d6fc1a215b6b4b787fad8819eb1b04b9a805c872c39999999999999999"
    "999999999999999999999999999999999999999999999999aaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbb"
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc"
    "ccccccccccccccccccccccccccccccccccccccccccccccccdddddddddddddddd"
    "dddddddddddddddddddddddddddddddddddddddddddddddd0000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000"
    "00000000000000000000000000000000395b397625edd6398134e18ec6ab655c"
    "07121a9b6dfe68cf8eabe30a13c57f314c2b5bb6f2d941c2a12379aee71d8a61"
    "16517bee2faa87f57ebb155143dd9565"
    ;


// kReadyInitiatorDigest (32 bytes)
constexpr const char* kReadyInitiatorDigest =
        "84af193a3ed10a2875f8df89e71c7613b1c864ee3078183806f0295acde983bb"
    ;


// kReadyInitiatorObjectHash (32 bytes)
constexpr const char* kReadyInitiatorObjectHash =
        "862c6db2ec80d39d7a24c77387b1eceef4e1428a98b63f000d52e38cb53212cf"
    ;


// kReadyResponderBytes (432 bytes)
constexpr const char* kReadyResponderBytes =
            "0001000000000000020102010000000011111111111111111111111111111111"
    "2222222222222222222222222222222201020304050607080000000000000000"
    "0000000000000007000000000000000000000000000000098888888888888888"
    "888888888888888888888888888888888888888888888888aa10adeee6a6d658"
    "6e444206382b47e52bbfd3e3155fb45648fe452c81c513759999999999999999"
    "999999999999999999999999999999999999999999999999aaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbb"
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc"
    "ccccccccccccccccccccccccccccccccccccccccccccccccdddddddddddddddd"
    "dddddddddddddddddddddddddddddddddddddddddddddddd0000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000002d82137345d0c8e907b6f2951545c6c6"
    "8dd28e0239cfc8e6942be6fe27cf8a634625a475908a6b9b804b0f66d09fe609"
    "9230198aac68244f2c663b59598538fb"
    ;


// kReadyResponderDigest (32 bytes)
constexpr const char* kReadyResponderDigest =
        "230aa59dd049fb78338b8a1b9451e7d5c329854656add2499ae19c5dfca3796f"
    ;


// kReadyResponderObjectHash (32 bytes)
constexpr const char* kReadyResponderObjectHash =
        "ced1b74ba80f57b34000d50542a7b454bc1b0f64a054f4f0730668af82236ebe"
    ;


// kAckInitiatorBytes (432 bytes)
constexpr const char* kAckInitiatorBytes =
            "0001000000000000010202020000000011111111111111111111111111111111"
    "2222222222222222222222222222222201020304050607080000000000000000"
    "0000000000000007000000000000000000000000000000098888888888888888"
    "888888888888888888888888888888888888888888888888e68b03ee77136754"
    "df1445d6fc1a215b6b4b787fad8819eb1b04b9a805c872c39999999999999999"
    "999999999999999999999999999999999999999999999999aaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbb"
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc"
    "ccccccccccccccccccccccccccccccccccccccccccccccccdddddddddddddddd"
    "dddddddddddddddddddddddddddddddddddddddddddddddd0000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000019ee9c72cd7c2b693e68cef78229f5e8"
    "3641d49d4779f6578f346c3f27275909583b7bfa1908c2d7bf5928b9c77db9f1"
    "f0ae030fffb561295201b73f3c8282bb"
    ;


// kAckInitiatorDigest (32 bytes)
constexpr const char* kAckInitiatorDigest =
        "0fb3caf5c5f812935c6ac12a02802639efd0dd1f045778bb8998b7f7d4fd0b9a"
    ;


// kAckInitiatorObjectHash (32 bytes)
constexpr const char* kAckInitiatorObjectHash =
        "adc9c09a6be6d2d0b9c9885bf5a0c285dee61ff2b5202be9e346b6eaf5862d08"
    ;

constexpr const char* kGenerator1 =
    "046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296"
    "4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5";
constexpr const char* kGenerator2 =
    "047cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc47669978"
    "07775510db8ed040293d9ac69f7430dbba7dade63ce982299e04b79d227873d1";

/*
 * The 16-byte channel identity used by every golden vector, zero-extended from
 * the former u64 fixture value 0x0102030405060708 by the independent oracle
 * (out/logs/gen_link_control_golden.py).
 */
constexpr std::array<std::uint8_t, 16> kGoldenChannelId = {{
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}};

std::uint8_t nibble(char value)
{
    return static_cast<std::uint8_t>(
        value <= '9' ? value - '0' : value - 'a' + 10);
}

template <std::size_t N>
std::array<std::uint8_t, N> hex_bytes(const char* hex)
{
    std::array<std::uint8_t, N> out{};
    for (std::size_t index = 0; index < N; ++index)
        out[index] = static_cast<std::uint8_t>(
            (nibble(hex[index * 2]) << 4u) | nibble(hex[index * 2 + 1]));
    return out;
}

std::array<std::uint8_t, 64> test_sign(
    const std::array<std::uint8_t, 65>& public_key,
    const std::array<std::uint8_t, 32>& digest)
{
    std::array<std::uint8_t, 64> out{};
    for (std::size_t part = 0; part < 2; ++part) {
        std::array<std::uint8_t, 1 + 65 + 32> buffer{};
        buffer[0] = static_cast<std::uint8_t>(part == 0 ? 1 : 2);
        std::copy(public_key.begin(), public_key.end(), buffer.begin() + 1);
        std::copy(digest.begin(), digest.end(), buffer.begin() + 66);
        const auto hash = wire::sha256(buffer.data(), buffer.size());
        std::copy(hash.begin(), hash.end(), out.begin() +
                                               static_cast<std::ptrdiff_t>(part * 32));
    }
    out[0] = static_cast<std::uint8_t>((out[0] & 0x7f) | 0x01);
    out[32] = static_cast<std::uint8_t>(0x40 | (out[32] & 0x1f));
    return out;
}

int verifier_calls = 0;

bool test_verify(void*, const std::uint8_t public_key[65],
                 const std::uint8_t digest[32],
                 const std::uint8_t signature[64])
{
    ++verifier_calls;
    std::array<std::uint8_t, 65> key{};
    std::copy_n(public_key, 65, key.begin());
    std::array<std::uint8_t, 32> message{};
    std::copy_n(digest, 32, message.begin());
    const auto expected = test_sign(key, message);
    return std::memcmp(expected.data(), signature, 64) == 0;
}

/* ------------------------------------------------------------- fixtures */

link::LinkReadyV1 golden_ready_value(link::LinkReadyPhaseV1 ready_phase)
{
    link::LinkReadyV1 value{};
    value.version = 1;
    value.sender_role = wire::PairRoleV1::Initiator;
    value.receiver_role = wire::PairRoleV1::Responder;
    value.phase = link::LinkPhaseV1::Reconcile;
    value.ready_phase = ready_phase;
    value.session_id.fill(0x11);
    value.link_id.fill(0x22);
    value.channel_id = kGoldenChannelId;
    value.connection_generation = 7;
    value.reconnect_attempt = 0;
    value.link_generation = 9;
    value.channel_bind_hash.fill(0x88);
    value.local_hello_object_hash = hex_bytes<32>(kHelloInitiatorObjectHash);
    value.peer_hello_object_hash.fill(0x99);
    value.negotiated_result_hash.fill(0xaa);
    value.local_summary_hash.fill(0xbb);
    value.peer_summary_hash.fill(0xcc);
    value.merge_result_hash.fill(0xdd);
    return value;
}

wire::LinkReadyExpectationsV1 ready_expectations(
    link::LinkReadyPhaseV1 expected_phase)
{
    wire::LinkReadyExpectationsV1 expected{};
    expected.session_id.fill(0x11);
    expected.link_id.fill(0x22);
    expected.channel_id = kGoldenChannelId;
    expected.connection_generation = 7;
    expected.reconnect_attempt = 0;
    expected.link_generation = 9;
    expected.local_role = wire::PairRoleV1::Responder;
    expected.expected_phase = expected_phase;
    expected.channel_bind_hash.fill(0x88);
    /* Mirrored check: the wire's local_hello_object_hash is the *sender's* own
     * HELLO, i.e. the peer HELLO this receiver verified, and the wire's
     * peer_hello_object_hash is this receiver's own HELLO, whose fixture object
     * hash is the constant 0x99.. used throughout this file. */
    expected.local_hello_object_hash.fill(0x99);
    expected.peer_hello_object_hash = hex_bytes<32>(kHelloInitiatorObjectHash);
    expected.negotiated_result_hash.fill(0xaa);
    /* Summaries are mirrored too: the sender's local summary is this receiver's
     * peer summary and vice versa. The fixture's responder-side summary is the
     * constant 0xcc.., so the sender's 0xbb.. local summary arrives as the peer
     * summary. The merge result is a shared result, so it is not mirrored. */
    expected.local_summary_hash.fill(0xcc);
    expected.peer_summary_hash.fill(0xbb);
    expected.merge_result_hash.fill(0xdd);
    expected.peer_session_signing_public_key = hex_bytes<65>(kGenerator1);
    return expected;
}

struct ReadyDecode
{
    wire::Status status = wire::Status::Ok;
    wire::LinkControlIssueV1 issue = wire::LinkControlIssueV1::None;
    link::LinkReadyV1 value{};
};

ReadyDecode decode_ready(const std::vector<std::uint8_t>& bytes,
                         const wire::LinkReadyExpectationsV1& expected)
{
    ReadyDecode out{};
    wire::LinkControlDecodeReportV1 report{};
    out.status = wire::decode_link_ready_v1(
        bytes.data(), bytes.size(), expected,
        wire::validate_p256_uncompressed_point_callback, nullptr, test_verify,
        nullptr, &report, &out.value);
    out.issue = report.issue;
    return out;
}

std::vector<std::uint8_t> bytes_of(const std::uint8_t* data, std::size_t size)
{
    return std::vector<std::uint8_t>(data, data + size);
}

/* ------------------------------------------------------------- positives */

void golden_ready_vectors()
{
    const auto expected_bytes = hex_bytes<432>(kReadyInitiatorBytes);
    const auto expected_digest = hex_bytes<32>(kReadyInitiatorDigest);
    const auto expected_object_hash = hex_bytes<32>(kReadyInitiatorObjectHash);

    auto value = golden_ready_value(link::LinkReadyPhaseV1::Ready);
    std::array<std::uint8_t, link::kLinkReadyPretagSizeV1> pretag{};
    std::array<std::uint8_t, 32> digest{};
    /* READY binds the sender's session signing key through the accepted
     * binding; the codec takes it as an expectation, not as a wire field. */
    value.signature.fill(0);
    check(wire::build_link_ready_pretag_v1(
              value, wire::validate_p256_uncompressed_point_callback, nullptr,
              &pretag, &digest) == wire::Status::Ok,
          "initiator READY pretag encodes");
    check(digest == expected_digest,
          "initiator READY digest equals the independent golden digest");

    const auto signature = test_sign(hex_bytes<65>(kGenerator1), expected_digest);
    std::array<std::uint8_t, link::kLinkReadySizeV1> bytes{};
    link::LinkReadyV1 parsed{};
    check(wire::finish_link_ready_v1(pretag, signature, &bytes, &parsed) ==
              wire::Status::Ok,
          "initiator READY finishes");
    check(bytes == expected_bytes,
          "initiator READY is byte-exact against the independent golden vector");
    check(parsed.object_hash == expected_object_hash,
          "initiator READY object hash equals the independent golden hash");

    verifier_calls = 0;
    auto decoded = decode_ready(bytes_of(bytes.data(), bytes.size()),
                                ready_expectations(link::LinkReadyPhaseV1::Ready));
    check(decoded.status == wire::Status::Ok && verifier_calls == 1,
          "initiator READY decodes with matching expectations");
    check(decoded.value.ready_phase == link::LinkReadyPhaseV1::Ready &&
              decoded.value.phase == link::LinkPhaseV1::Reconcile,
          "decoded READY carries phase RECONCILE and ready phase READY");

    /* The mirrored responder vector. */
    link::LinkReadyV1 responder{};
    responder.sender_role = wire::PairRoleV1::Responder;
    responder.receiver_role = wire::PairRoleV1::Initiator;
    responder.session_id.fill(0x11);
    responder.link_id.fill(0x22);
    responder.channel_id = kGoldenChannelId;
    responder.connection_generation = 7;
    responder.reconnect_attempt = 0;
    responder.link_generation = 9;
    responder.channel_bind_hash.fill(0x88);
    responder.local_hello_object_hash = hex_bytes<32>(kHelloResponderObjectHash);
    responder.peer_hello_object_hash.fill(0x99);
    responder.negotiated_result_hash.fill(0xaa);
    responder.local_summary_hash.fill(0xbb);
    responder.peer_summary_hash.fill(0xcc);
    responder.merge_result_hash.fill(0xdd);
    std::array<std::uint8_t, link::kLinkReadyPretagSizeV1> responder_pretag{};
    std::array<std::uint8_t, 32> responder_digest{};
    check(wire::build_link_ready_pretag_v1(
              responder, wire::validate_p256_uncompressed_point_callback,
              nullptr, &responder_pretag, &responder_digest) == wire::Status::Ok,
          "responder READY pretag encodes");
    check(responder_digest == hex_bytes<32>(kReadyResponderDigest),
          "responder READY digest equals the independent golden digest");
    const auto responder_signature =
        test_sign(hex_bytes<65>(kGenerator2), responder_digest);
    std::array<std::uint8_t, link::kLinkReadySizeV1> responder_bytes{};
    link::LinkReadyV1 responder_parsed{};
    check(wire::finish_link_ready_v1(responder_pretag, responder_signature,
                                     &responder_bytes,
                                     &responder_parsed) == wire::Status::Ok,
          "responder READY finishes");
    check(responder_bytes == hex_bytes<432>(kReadyResponderBytes),
          "responder READY is byte-exact against the independent golden vector");
    check(responder_parsed.object_hash ==
              hex_bytes<32>(kReadyResponderObjectHash),
          "responder READY object hash equals the independent golden hash");
}

void golden_ack_vector()
{
    const auto expected_bytes = hex_bytes<432>(kAckInitiatorBytes);
    const auto expected_digest = hex_bytes<32>(kAckInitiatorDigest);
    const auto expected_object_hash = hex_bytes<32>(kAckInitiatorObjectHash);

    auto value = golden_ready_value(link::LinkReadyPhaseV1::Ack);
    std::array<std::uint8_t, link::kLinkReadyPretagSizeV1> pretag{};
    std::array<std::uint8_t, 32> digest{};
    check(wire::build_link_ready_pretag_v1(
              value, wire::validate_p256_uncompressed_point_callback, nullptr,
              &pretag, &digest) == wire::Status::Ok,
          "ACK pretag encodes");
    check(digest == expected_digest,
          "ACK digest equals the independent golden digest");
    const auto signature = test_sign(hex_bytes<65>(kGenerator1), expected_digest);
    std::array<std::uint8_t, link::kLinkReadySizeV1> bytes{};
    link::LinkReadyV1 parsed{};
    check(wire::finish_link_ready_v1(pretag, signature, &bytes, &parsed) ==
              wire::Status::Ok,
          "ACK finishes");
    check(bytes == expected_bytes,
          "ACK is byte-exact against the independent golden vector");
    check(parsed.object_hash == expected_object_hash,
          "ACK object hash equals the independent golden hash");
    check(bytes[11] == 2, "ACK carries ready_phase Ack at offset 11");

    const auto decoded = decode_ready(
        bytes_of(bytes.data(), bytes.size()),
        ready_expectations(link::LinkReadyPhaseV1::Ack));
    check(decoded.status == wire::Status::Ok,
          "ACK decodes when an ACK is expected");

    /* A READY must not be accepted where an ACK is required, and vice versa. */
    const auto ready_bytes = hex_bytes<432>(kReadyInitiatorBytes);
    const auto wrong_phase = decode_ready(
        bytes_of(ready_bytes.data(), ready_bytes.size()),
        ready_expectations(link::LinkReadyPhaseV1::Ack));
    check(wrong_phase.status == wire::Status::InvalidField &&
              wrong_phase.issue == wire::LinkControlIssueV1::Discriminant,
          "a READY is rejected where an ACK is required");
    const auto ack_bytes = hex_bytes<432>(kAckInitiatorBytes);
    const auto wrong_phase2 = decode_ready(
        bytes_of(ack_bytes.data(), ack_bytes.size()),
        ready_expectations(link::LinkReadyPhaseV1::Ready));
    check(wrong_phase2.status == wire::Status::InvalidField &&
              wrong_phase2.issue == wire::LinkControlIssueV1::Discriminant,
          "an ACK is rejected where a READY is required");
}

void exact_field_offsets()
{
    const auto bytes = hex_bytes<432>(kReadyInitiatorBytes);
    check(bytes[0] == 0x00 && bytes[1] == 0x01,
          "READY version is u16be 1 at offset 0");
    check(bytes[8] == 1 && bytes[9] == 2 && bytes[10] == 2 && bytes[11] == 1,
          "READY roles, phase and ready phase sit at offsets 8..12");
    check(bytes[16] == 0x11 && bytes[32] == 0x22,
          "READY session and link ids sit at offsets 16/32");
    check(bytes[48] == 0x01 && bytes[55] == 0x08,
          "READY channel_id starts at offset 48 with the derive_channel_id_v1 bytes");
    check(bytes[56] == 0x00 && bytes[63] == 0x00,
          "READY channel_id is 16 bytes wide, zero-extended at offsets 56..64");
    check(bytes[64] == 0x00 && bytes[71] == 0x07,
          "READY connection_generation is u64be at offset 64");
    check(bytes[72] == 0 && bytes[79] == 0,
          "READY reconnect_attempt is zero at offset 72");
    check(bytes[80] == 0 && bytes[87] == 0x09,
          "READY link_generation is u64be at offset 80");
    check(bytes[88] == 0x88 && bytes[120] != 0 && bytes[152] != 0 &&
              bytes[184] == 0xaa,
          "READY hash block is contiguous at offset 88");
    check(bytes[216] == 0xbb && bytes[248] == 0xcc && bytes[280] == 0xdd,
          "READY summary and merge hashes sit at offsets 216/248/280");
    check(std::all_of(bytes.begin() + 312, bytes.begin() + 368,
                      [](std::uint8_t value) { return value == 0; }),
          "READY reserved block before the signature is zeroed");
    check(bytes[368] != 0 && bytes[431] != 0,
          "READY signature occupies offsets 368..432");
}

void negotiated_result_domain()
{
    std::array<std::uint8_t, 96> result{};
    result.fill(0x5a);
    std::array<std::uint8_t, 32> hash{};
    check(wire::hash_link_negotiated_result_v1(result.data(), result.size(),
                                               &hash) == wire::Status::Ok &&
              hash == wire::domain_hash(link::kLinkNegotiatedResultHashDomainV1,
                                        result.data(), result.size()),
          "negotiated result hash uses the frozen contract domain");
    check(hash != wire::domain_hash(link::kLinkReadyDigestDomainV1,
                                    result.data(), result.size()),
          "negotiated result hash is domain-separated from READY");
    check(wire::hash_link_negotiated_result_v1(nullptr, 0, &hash) ==
              wire::Status::InvalidField,
          "negotiated result hash rejects an empty input");
    check(wire::hash_link_negotiated_result_v1(result.data(), result.size(),
                                               nullptr) ==
              wire::Status::InvalidField,
          "negotiated result hash rejects a null output");
}

/* ------------------------------------------------------------- negatives */

void structural_negatives()
{
    const auto golden = hex_bytes<432>(kReadyInitiatorBytes);
    const auto expected = ready_expectations(link::LinkReadyPhaseV1::Ready);

    auto truncated = bytes_of(golden.data(), golden.size());
    truncated.pop_back();
    check(decode_ready(truncated, expected).status == wire::Status::Truncated,
          "READY rejects truncation");

    auto trailing = bytes_of(golden.data(), golden.size());
    trailing.push_back(0);
    check(decode_ready(trailing, expected).status == wire::Status::Trailing,
          "READY rejects trailing bytes");

    struct Mutation
    {
        std::size_t offset;
        const char* message;
    };
    const Mutation reserved[] = {
        {3, "READY rejects nonzero reserved byte 3"},
        {12, "READY rejects nonzero reserved byte 12"},
        {313, "READY rejects nonzero reserved byte 313"}};
    for (const auto& mutation : reserved) {
        auto bytes = bytes_of(golden.data(), golden.size());
        bytes[mutation.offset] = 1;
        const auto decoded = decode_ready(bytes, expected);
        check(decoded.status == wire::Status::NonzeroReserved &&
                  decoded.issue == wire::LinkControlIssueV1::Reserved,
              mutation.message);
    }

    auto version = bytes_of(golden.data(), golden.size());
    version[1] = 2;
    check(decode_ready(version, expected).status == wire::Status::UnknownEnum,
          "READY rejects an unknown object version");

    auto unknown_phase = bytes_of(golden.data(), golden.size());
    unknown_phase[10] = 9;
    check(decode_ready(unknown_phase, expected).status ==
              wire::Status::UnknownEnum,
          "READY rejects an unknown phase");

    /* READY is only legal in phase RECONCILE. */
    auto initial_phase = bytes_of(golden.data(), golden.size());
    initial_phase[10] = 1;
    check(decode_ready(initial_phase, expected).status ==
              wire::Status::InvalidField,
          "READY rejects phase INITIAL");

    auto unknown_ready_phase = bytes_of(golden.data(), golden.size());
    unknown_ready_phase[11] = 9;
    check(decode_ready(unknown_ready_phase, expected).status ==
              wire::Status::UnknownEnum,
          "READY rejects an unknown ready phase");

    auto sender = bytes_of(golden.data(), golden.size());
    sender[8] = 3;
    check(decode_ready(sender, expected).status == wire::Status::UnknownEnum,
          "READY rejects an unknown sender role");

    auto receiver = bytes_of(golden.data(), golden.size());
    receiver[9] = 3;
    check(decode_ready(receiver, expected).status == wire::Status::UnknownEnum,
          "READY rejects an unknown receiver role");

    auto unmirrored = bytes_of(golden.data(), golden.size());
    unmirrored[9] = 1;
    check(decode_ready(unmirrored, expected).status ==
              wire::Status::InvalidField,
          "READY rejects unmirrored roles");

    auto reversed = bytes_of(golden.data(), golden.size());
    reversed[8] = 2;
    reversed[9] = 1;
    check(decode_ready(reversed, expected).status == wire::Status::InvalidField,
          "READY rejects reflected roles");
}

void binding_chain_negatives()
{
    const auto golden = hex_bytes<432>(kReadyInitiatorBytes);
    const auto expected = ready_expectations(link::LinkReadyPhaseV1::Ready);

    struct Mutation
    {
        std::size_t offset;
        wire::LinkControlIssueV1 issue;
        const char* message;
    };
    const Mutation mismatches[] = {
        {16, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different session id"},
        {32, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different link id"},
        {55, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different channel id"},
        {59, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different 16-byte channel id"},
        {71, wire::LinkControlIssueV1::Generation,
         "READY rejects a different connection generation"},
        {79, wire::LinkControlIssueV1::Generation,
         "READY rejects a different reconnect attempt"},
        {87, wire::LinkControlIssueV1::Generation,
         "READY rejects a different link generation"},
        {88, wire::LinkControlIssueV1::BindingRef,
         "READY rejects a different channel bind hash"},
        {120, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different local HELLO object hash"},
        {152, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different peer HELLO object hash"},
        {184, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different negotiated result hash"},
        {216, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different local summary hash"},
        {248, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different peer summary hash"},
        {280, wire::LinkControlIssueV1::ExpectedField,
         "READY rejects a different merge result hash"},
        {184 + 31, wire::LinkControlIssueV1::ExpectedField,
         "READY binds the negotiated result hash byte-for-byte"}};
    for (const auto& mutation : mismatches) {
        auto bytes = bytes_of(golden.data(), golden.size());
        bytes[mutation.offset] ^= 0x01;
        const auto decoded = decode_ready(bytes, expected);
        check(decoded.status == wire::Status::InvalidField &&
                  decoded.issue == mutation.issue,
              mutation.message);
    }

    /* A one-sided READY whose peer-hello hash names a HELLO this side never
     * verified must be rejected: only the mirrored pair is legal. */
    auto one_sided = bytes_of(golden.data(), golden.size());
    std::fill(one_sided.begin() + 152, one_sided.begin() + 184, std::uint8_t{0});
    const auto one_sided_decoded = decode_ready(one_sided, expected);
    check(one_sided_decoded.status == wire::Status::InvalidField &&
              one_sided_decoded.issue == wire::LinkControlIssueV1::ExpectedField,
          "READY rejects a zeroed peer HELLO hash");
}

void signature_negatives()
{
    const auto golden = hex_bytes<432>(kReadyInitiatorBytes);
    const auto expected = ready_expectations(link::LinkReadyPhaseV1::Ready);
    const auto digest = hex_bytes<32>(kReadyInitiatorDigest);

    auto zeroed = bytes_of(golden.data(), golden.size());
    std::fill(zeroed.begin() + 368, zeroed.end(), std::uint8_t{0});
    verifier_calls = 0;
    auto decoded = decode_ready(zeroed, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Signature &&
              verifier_calls == 0,
          "READY rejects a zeroed signature without calling the verifier");

    auto high_s = bytes_of(golden.data(), golden.size());
    high_s[400] = 0x80;
    verifier_calls = 0;
    decoded = decode_ready(high_s, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Signature &&
              verifier_calls == 0,
          "READY rejects a non-canonical high-S signature before verifying");

    auto double_hashed = bytes_of(golden.data(), golden.size());
    {
        const auto inner = wire::sha256(digest.data(), digest.size());
        const auto bad = test_sign(hex_bytes<65>(kGenerator1), inner);
        std::copy(bad.begin(), bad.end(), double_hashed.begin() + 368);
    }
    decoded = decode_ready(double_hashed, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Signature,
          "READY rejects a double-hashed signature");

    auto wrong_purpose = bytes_of(golden.data(), golden.size());
    {
        const auto hello_digest = wire::domain_hash(
            link::kLinkHelloDigestDomainV1, golden.data(),
            link::kLinkReadyPretagSizeV1);
        const auto bad = test_sign(hex_bytes<65>(kGenerator1), hello_digest);
        std::copy(bad.begin(), bad.end(), wrong_purpose.begin() + 368);
    }
    decoded = decode_ready(wrong_purpose, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Signature,
          "READY rejects a signature made under the HELLO domain");

    /* A signature by the long-term identity key instead of the session signing
     * key must fail: only the binding-authenticated session key signs control
     * traffic. */
    auto identity_signed = bytes_of(golden.data(), golden.size());
    {
        const auto bad = test_sign(hex_bytes<65>(kGenerator2), digest);
        std::copy(bad.begin(), bad.end(), identity_signed.begin() + 368);
    }
    decoded = decode_ready(identity_signed, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Signature,
          "READY rejects a long-term identity signature");

    /* A reflected sender role that is re-signed is still rejected. */
    auto reflected = bytes_of(golden.data(), golden.size());
    reflected[8] = 2;
    reflected[9] = 1;
    {
        const auto reflected_digest = wire::domain_hash(
            link::kLinkReadyDigestDomainV1, reflected.data(),
            link::kLinkReadyPretagSizeV1);
        const auto bad = test_sign(hex_bytes<65>(kGenerator1), reflected_digest);
        std::copy(bad.begin(), bad.end(), reflected.begin() + 368);
    }
    verifier_calls = 0;
    decoded = decode_ready(reflected, expected);
    check(decoded.status == wire::Status::InvalidField &&
              decoded.issue == wire::LinkControlIssueV1::Discriminant &&
              verifier_calls == 0,
          "READY rejects a signed but reflected role assignment");

    wire::LinkControlDecodeReportV1 report{};
    link::LinkReadyV1 value{};
    check(wire::decode_link_ready_v1(
              golden.data(), golden.size(), expected,
              wire::validate_p256_uncompressed_point_callback, nullptr, nullptr,
              nullptr, &report, &value) == wire::Status::InvalidField,
          "READY refuses to decode without a signature verifier");
}

void wrong_kind()
{
    const auto ready = hex_bytes<432>(kReadyInitiatorBytes);
    wire::LinkControlDecodeReportV1 report{};
    link::LinkHelloV1 hello_value{};
    wire::LinkHelloExpectationsV1 hello_expected{};
    check(wire::decode_link_hello_v1(
              ready.data(), ready.size(), hello_expected,
              wire::validate_p256_uncompressed_point_callback, nullptr,
              test_verify, nullptr, &report, &hello_value) ==
              wire::Status::Truncated,
          "LINK_READY bytes are not accepted as a LINK_HELLO object");
    check(link::kLinkReadyObjectKindV1 == 0x0217,
          "READY object kind comes from the frozen contract");
    check(std::strcmp(link::kLinkReadyDigestDomainV1, "flynes-link-ready-v1") ==
              0 &&
              std::strcmp(link::kLinkReadyObjectHashDomainV1,
                          "flynes-link-ready-object-v1") == 0,
          "READY domains come from the frozen contract");
}

/*
 * The two-stage contract for READY/ACK: stage 1 validates every
 * non-cryptographic field and hands back the exact verification request; stage 2
 * accepts or fails closed once the asynchronous verification result exists.
 */
void two_stage_parse_then_accept()
{
    const auto expected = ready_expectations(link::LinkReadyPhaseV1::Ready);
    const auto golden = hex_bytes<432>(kReadyInitiatorBytes);

    wire::LinkControlDecodeReportV1 report{};
    wire::LinkControlParsedV1 parsed{};
    link::LinkReadyV1 value{};
    check(wire::parse_link_ready_v1(
              golden.data(), golden.size(), expected,
              wire::validate_p256_uncompressed_point_callback, nullptr, &report,
              &parsed, &value) == wire::Status::Ok,
          "stage 1 parses a well-formed READY without any cryptography");

    const auto expected_digest = hex_bytes<32>(kReadyInitiatorDigest);
    const auto expected_object_hash = hex_bytes<32>(kReadyInitiatorObjectHash);
    check(parsed.digest == expected_digest &&
              value.digest == expected_digest &&
              value.object_hash == expected_object_hash,
          "stage 1 already fixes the exact READY digest and object hash");

    wire::LinkControlVerifyRequestV1 request{};
    const std::string digest_domain = link::kLinkReadyDigestDomainV1;
    check(wire::link_control_verify_request_v1(
              parsed, link::kLinkReadyDigestDomainV1, &request) ==
              wire::Status::Ok &&
              request.public_key_x963 ==
                  expected.peer_session_signing_public_key &&
              request.digest == expected_digest &&
              request.signature == parsed.signature &&
              request.domain.size() == digest_domain.size() &&
              std::equal(request.domain.begin(), request.domain.end(),
                         digest_domain.begin()),
          "stage 1 produces the exact asynchronous verification request");

    link::LinkReadyV1 accepted{};
    check(wire::accept_link_ready_v1(
              parsed, value, wire::LinkControlVerificationOutcomeV1::Accepted,
              &report, &accepted) == wire::Status::Ok &&
              accepted.object_hash == expected_object_hash,
          "stage 2 accepts after a successful asynchronous verification");

    link::LinkReadyV1 rejected{};
    report = wire::LinkControlDecodeReportV1{};
    check(wire::accept_link_ready_v1(
              parsed, value, wire::LinkControlVerificationOutcomeV1::Rejected,
              &report, &rejected) == wire::Status::InvalidField &&
              report.issue == wire::LinkControlIssueV1::Signature,
          "stage 2 fails closed when the asynchronous verifier rejected");

    /* Structurally valid but wrong signature: accepted by stage 1, rejected only
     * by stage 2. This is the moved rejection point. */
    auto tampered = bytes_of(golden.data(), golden.size());
    tampered[372] = static_cast<std::uint8_t>(tampered[372] ^ 0x01u);
    wire::LinkControlDecodeReportV1 tampered_report{};
    wire::LinkControlParsedV1 tampered_parsed{};
    link::LinkReadyV1 tampered_value{};
    check(wire::parse_link_ready_v1(
              tampered.data(), tampered.size(), expected,
              wire::validate_p256_uncompressed_point_callback, nullptr,
              &tampered_report, &tampered_parsed, &tampered_value) ==
              wire::Status::Ok,
          "stage 1 defers the READY signature decision to stage 2");
    wire::LinkControlDecodeReportV1 tampered_accept_report{};
    link::LinkReadyV1 tampered_accepted{};
    check(wire::accept_link_ready_v1(
              tampered_parsed, tampered_value,
              wire::LinkControlVerificationOutcomeV1::Rejected,
              &tampered_accept_report, &tampered_accepted) ==
              wire::Status::InvalidField &&
              tampered_accept_report.issue == wire::LinkControlIssueV1::Signature,
          "a tampered READY signature is rejected only after the async result");

    /* The non-cryptographic negatives stay in stage 1. */
    auto reflected = bytes_of(golden.data(), golden.size());
    reflected[8] = 2;
    reflected[9] = 1;
    wire::LinkControlDecodeReportV1 reflected_report{};
    wire::LinkControlParsedV1 reflected_parsed{};
    link::LinkReadyV1 reflected_value{};
    check(wire::parse_link_ready_v1(
              reflected.data(), reflected.size(), expected,
              wire::validate_p256_uncompressed_point_callback, nullptr,
              &reflected_report, &reflected_parsed, &reflected_value) ==
              wire::Status::InvalidField &&
              reflected_report.issue == wire::LinkControlIssueV1::Discriminant,
          "stage 1 still rejects a role-reflected READY before any crypto");

    auto zero_signature = bytes_of(golden.data(), golden.size());
    std::fill(zero_signature.begin() + 368, zero_signature.end(), 0);
    wire::LinkControlDecodeReportV1 zero_report{};
    wire::LinkControlParsedV1 zero_parsed{};
    link::LinkReadyV1 zero_value{};
    check(wire::parse_link_ready_v1(
              zero_signature.data(), zero_signature.size(), expected,
              wire::validate_p256_uncompressed_point_callback, nullptr,
              &zero_report, &zero_parsed, &zero_value) ==
              wire::Status::InvalidField &&
              zero_report.issue == wire::LinkControlIssueV1::Signature,
          "stage 1 still rejects a non-canonical zero READY signature");
}

} // namespace

int main()
{
    golden_ready_vectors();
    golden_ack_vector();
    exact_field_offsets();
    negotiated_result_domain();
    structural_negatives();
    binding_chain_negatives();
    signature_negatives();
    wrong_kind();
    two_stage_parse_then_accept();

    if (failures != 0) {
        std::fprintf(stderr, "%d link ready codec checks failed\n", failures);
        return 1;
    }
    std::puts("link ready codec tests passed");
    return 0;
}
