#!/usr/bin/env python3
"""Validate bilingual metadata, generate the native table, and audit a private corpus.

Uses only the Python standard library. Corpus access is read-only; ZIP contents
are streamed in memory and never extracted or copied into the repository.
"""
import argparse
import csv
import hashlib
import json
from pathlib import Path
import re
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / 'shared/data/game_titles.json'
DEFAULT_OUTPUT = ROOT / 'shared/data/game_titles.inc'


def validate(data):
    if data.get('schema_version') != 1 or not isinstance(data.get('entries'), list):
        raise ValueError('unsupported metadata schema')
    if 'corpus' in data:
        counts = data['corpus']
        if counts.get('unique_roms') != len(data['entries']) or counts.get('manifest_rows', 0) < len(data['entries']):
            raise ValueError('declared corpus count does not match metadata')
    seen = set()
    for entry in data['entries']:
        sha = entry.get('sha256', '')
        if not re.fullmatch('[0-9a-f]{64}', sha):
            raise ValueError('invalid lowercase full-ROM sha256')
        if sha in seen:
            raise ValueError('duplicate sha256: ' + sha)
        seen.add(sha)
        if entry.get('id') != 'nes-' + sha:
            raise ValueError('id must be derived from the full sha256')
        for language in ('en', 'zh'):
            title = entry.get(language)
            if not isinstance(title, str) or not title.strip():
                raise ValueError(language + ' title is required')
            if re.search(r'unknown game|untitled|placeholder|ZZZ_UNK|need correct title', title, re.I):
                raise ValueError('placeholder title: ' + sha)
        if not re.search('[A-Za-z0-9]', entry['en']) or re.search('[\u3400-\u9fff\u2500-\u259f]', entry['en']):
            raise ValueError('English title must be readable English or romanization: ' + sha)
        if entry.get('english_source') not in ('source_filename', 'local_crc_title', 'curated', 'translation'):
            raise ValueError('English title provenance is required')
        aliases = entry.get('aliases')
        if not isinstance(aliases, list) or any(not isinstance(s, str) or not s for s in aliases):
            raise ValueError('aliases must be nonempty strings')
        if len(aliases) != len(set(aliases)):
            raise ValueError('duplicate aliases: ' + sha)
        for value in [entry['en'], entry['zh'], *aliases]:
            if re.search(r'^[A-Za-z]:[/\\]|^[/\\]|\.\.[/\\]|\.(?:nes|fds|zip)$', value, re.I):
                raise ValueError('local path or ROM filename in metadata: ' + sha)
            if any(ord(c) < 32 for c in value):
                raise ValueError('control character in metadata: ' + sha)
    return seen


def render(data):
    validate(data)
    lines = ['// Generated by tools/game_titles/game_titles.py; edit game_titles.json.',
             '// Full uncompressed ROM SHA-256; no ROM content is included.']
    for entry in sorted(data['entries'], key=lambda item: item['sha256']):
        fields = [entry['sha256'], entry['id'], entry['en'], entry['zh'], '\n'.join(entry['aliases'])]
        lines.append('FLYNES_GAME_TITLE(' + ', '.join(json.dumps(s, ensure_ascii=False) for s in fields) + ')')
    return '\n'.join(lines) + '\n'


def verify_corpus(corpus, manifest, data):
    indexed = validate(data)
    corpus = Path(corpus).resolve()
    with Path(manifest).open(encoding='utf-8-sig', newline='') as stream:
        rows = list(csv.DictReader(stream))
    errors, verified_hashes, expected_names = [], set(), set()
    verified = 0
    for row in rows:
        name = row['output']
        archive_path = (corpus / name).resolve()
        if not archive_path.is_relative_to(corpus) or archive_path.parent != corpus:
            errors.append('invalid manifest archive path')
            continue
        if name in expected_names:
            errors.append('duplicate manifest output: ' + name)
        expected_names.add(name)
        expected_hash = row['sha256'].lower()
        if expected_hash not in indexed:
            errors.append('unindexed manifest hash: ' + expected_hash)
        try:
            with zipfile.ZipFile(archive_path) as archive:
                members = [m for m in archive.infolist() if not m.is_dir() and Path(m.filename).suffix.lower() in ('.nes', '.fds', '.unf', '.unif')]
                if len(members) != 1:
                    errors.append('expected exactly one ROM member: ' + name)
                    continue
                digest, size = hashlib.sha256(), 0
                with archive.open(members[0]) as stream:
                    for chunk in iter(lambda: stream.read(1024 * 1024), b''):
                        digest.update(chunk)
                        size += len(chunk)
                actual_hash = digest.hexdigest()
                if actual_hash != expected_hash:
                    errors.append('hash mismatch: ' + name)
                elif size != int(row['size']):
                    errors.append('size mismatch: ' + name)
                else:
                    verified += 1
                    verified_hashes.add(actual_hash)
        except (OSError, ValueError, zipfile.BadZipFile, RuntimeError) as error:
            errors.append('cannot verify ' + name + ': ' + type(error).__name__)
    actual_names = {p.name for p in corpus.glob('*.zip')}
    errors.extend('unmanifested archive: ' + name for name in sorted(actual_names - expected_names))
    manifest_hashes = {r['sha256'].lower() for r in rows}
    errors.extend('index hash absent from corpus: ' + sha for sha in sorted(indexed - manifest_hashes))
    return dict(manifest_rows=len(rows), archive_count=len(actual_names), index_entries=len(indexed),
                verified_archives=verified, verified_unique_hashes=len(verified_hashes),
                manifest_sha256=hashlib.sha256(Path(manifest).read_bytes()).hexdigest(), errors=errors)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=('generate', 'check', 'verify-corpus'))
    parser.add_argument('--source', type=Path, default=DEFAULT_SOURCE)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--corpus', type=Path)
    parser.add_argument('--manifest', type=Path)
    parser.add_argument('--report', type=Path)
    args = parser.parse_args(argv)
    try:
        data = json.loads(args.source.read_text(encoding='utf-8'))
        generated = render(data)
        if args.command == 'generate':
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(generated, encoding='utf-8', newline='\n')
        elif args.command == 'check':
            if not args.output.exists() or args.output.read_bytes() != generated.encode('utf-8'):
                raise ValueError('generated table is stale; run generate')
        else:
            if not args.corpus:
                parser.error('verify-corpus requires --corpus')
            report = verify_corpus(args.corpus, args.manifest or args.corpus / 'manifest.csv', data)
            output = json.dumps(report, ensure_ascii=False, indent=2) + '\n'
            if args.report:
                args.report.parent.mkdir(parents=True, exist_ok=True)
                args.report.write_text(output, encoding='utf-8')
            print(output, end='')
            return bool(report['errors'])
        print(f'{args.command}: {len(data["entries"])} bilingual entries validated')
        return 0
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
