package com.flynes.emu.video.quality;

public enum EvidenceInvalidReason {
    NONE,
    CERTIFICATE_MISSING,
    PROFILE_MISMATCH,
    CONFIGURATION_MISMATCH,
    BUILD_OR_DRIVER_MISMATCH,
    IMPLEMENTATION_MISMATCH,
    MANIFEST_MISMATCH,
    EVIDENCE_LEVEL_INSUFFICIENT,
    INVALID_VALIDITY_RANGE,
    VALIDITY_TOO_LONG,
    CLOCK_STATE_CORRUPT,
    EVIDENCE_TOMBSTONED,
    TIME_BOOTSTRAP_REQUIRED,
    TIME_UNTRUSTED,
    FUTURE_ISSUED,
    EVIDENCE_EXPIRED
}
