package com.flynes.emu.video.quality;

public enum FallbackReason {
    DISPLAY_MODE_UNAVAILABLE,
    DISPLAY_MODE_REJECTED,
    DISPLAY_OBSERVATION_STALE,
    SYSTEM_OR_DEVICE_POLICY,
    BUILD_UNAVAILABLE,
    GL_CAPABILITY_UNVERIFIED,
    CONFIGURATION_UNVERIFIED,
    RUNTIME_FAILURE,
    THERMAL_SAFETY,
    BATTERY_SAFETY,
    TIME_BOOTSTRAP_REQUIRED,
    TIME_UNTRUSTED,
    EVIDENCE_EXPIRED
}
