[CmdletBinding()]
param(
    [string] $RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..')).Path,
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $RepoRoot 'docs\acceptance\display-quality\mmpx-oracle-manifest.json'
}

$oraclePath = 'app/src/test/java/com/flynes/emu/video/reference/MmpxCpuOracle.java'
$noticePath = 'app/src/test/java/com/flynes/emu/video/reference/MMPX_SOURCE_NOTICE.md'
$fixtureRelativeRoot = 'app/src/test/resources/spatial-golden/oracle'
$fixtureRoot = Join-Path $RepoRoot ($fixtureRelativeRoot.Replace('/', '\'))

function Get-CanonicalTextInfo {
    param([Parameter(Mandatory = $true)][string] $RelativePath)

    $absolutePath = Join-Path $RepoRoot ($RelativePath.Replace('/', '\'))
    if (-not (Test-Path -LiteralPath $absolutePath -PathType Leaf)) {
        throw "MMPX oracle manifest input is missing: $RelativePath"
    }
    $canonicalText = [System.IO.File]::ReadAllText($absolutePath).Replace("`r`n", "`n").Replace("`r", "`n")
    $bytes = [System.Text.UTF8Encoding]::new($false).GetBytes($canonicalText)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hash = [System.BitConverter]::ToString($sha.ComputeHash($bytes)).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $sha.Dispose()
    }
    return [pscustomobject]@{
        path = $RelativePath
        canonicalSha256 = $hash
        canonicalSizeBytes = $bytes.Length
    }
}

if (-not (Test-Path -LiteralPath $fixtureRoot -PathType Container)) {
    throw "MMPX fixture directory is missing: $fixtureRelativeRoot"
}
$unexpectedFixtureFiles = @(Get-ChildItem -LiteralPath $fixtureRoot -File |
    Where-Object { $_.Extension -ne '.fixture' })
if ($unexpectedFixtureFiles.Count -gt 0) {
    throw "Unrecognized file in frozen MMPX fixture directory: $($unexpectedFixtureFiles.Name -join ', ')"
}
$fixturePaths = @(Get-ChildItem -LiteralPath $fixtureRoot -Filter '*.fixture' -File |
    ForEach-Object { "$fixtureRelativeRoot/$($_.Name)" } | Sort-Object)
if ($fixturePaths.Count -eq 0) {
    throw 'The MMPX oracle manifest cannot be generated without fixtures.'
}

$files = @($oraclePath, $noticePath) + $fixturePaths | ForEach-Object {
    Get-CanonicalTextInfo -RelativePath $_
}
$manifest = [ordered]@{
    schemaVersion = 1
    generatorVersion = 'flynes-mmpx-oracle-manifest-v1'
    oracleVersion = 'MMPX-2X-JCGT-2021-SUPPLEMENT'
    sourceArchiveSha256 = '1211c4b59d5bea3c5ebeb1dc3b31fe8a2f0c58f64955cee50e939f96543996e1'
    pixelPacking = 'AABBGGRR'
    fixtureProvenance = 'Original FlyNES synthetic patterns; expected arrays generated by the pinned official JavaScript reference.'
    files = @($files)
}

$json = ($manifest | ConvertTo-Json -Depth 8).Replace("`r`n", "`n") + "`n"
$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
[System.IO.File]::WriteAllText($OutputPath, $json, [System.Text.UTF8Encoding]::new($false))
